import { FoodItem } from './type';

export const foodItems: FoodItem[] = [
  {
    id: '0',
    title: 'Tarte au citron meringuée',
    description:
      'Un dessert classique avec une base croustillante, une crème au citron onctueuse et une meringue légère.',
    category: 'Gâteau',
    price: 20000,
    ingredients: ['Farine', 'Beurre', 'Œufs', 'Citron', 'Sucre', 'Sel'],
    preparationTime: 90,
    rating: 4.9,
    isAvailable: true,
  },
  {
    id: '1',
    title: 'Koba Ravina',
    description:
      'Gâteau traditionnel malgache à base de cacahuètes, bananes et riz enveloppé dans des feuilles de bananier.',
    category: 'Gâteau',
    price: 5000,
    ingredients: [
      'Cacahuètes',
      'Bananes',
      'Riz',
      'Feuilles de bananier',
      'Miel',
    ],
    preparationTime: 120,
    rating: 4.8,
    isAvailable: true,
  },
  {
    id: '2',
    title: 'Éclair au chocolat',
    description:
      'Pâtisserie à base de pâte à choux garnie de crème pâtissière au chocolat.',
    category: 'Snacks',
    price: 15000,
    ingredients: ['Farine', 'Beurre', 'Œufs', 'Chocolat noir', 'Lait', 'Crème'],
    preparationTime: 45,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: '3',
    title: 'Godrogodro',
    description: 'Gâteau de riz gluant avec du lait de coco et du caramel.',
    category: 'Gâteau',
    price: 6000,
    ingredients: ['Riz gluant', 'Lait de coco', 'Sucre', 'Vanille'],
    preparationTime: 90,
    rating: 4.9,
    isAvailable: true,
  },
  {
    id: '4',
    title: 'Macaron à la vanille de Madagascar',
    description:
      "Biscuits délicats à base d'amandes avec une ganache à la vanille de Madagascar.",
    category: 'Snacks',
    price: 10000,
    ingredients: [
      "Poudre d'amande",
      'Sucre glace',
      "Blanc d'œuf",
      'Vanille de Madagascar',
      'Crème',
    ],
    preparationTime: 120,
    rating: 4.8,
    isAvailable: true,
  },
  {
    id: '5',
    title: 'Mofo Banana',
    description: 'Beignets de bananes traditionnels malgaches.',
    category: 'Gâteau',
    price: 2000,
    ingredients: ['Bananes', 'Farine', 'Sucre', 'Levure', 'Huile'],
    preparationTime: 30,
    rating: 4.6,
    isAvailable: true,
  },
  {
    id: '6',
    title: 'Paris-Brest',
    description:
      'Couronne de pâte à choux fourrée de crème pralinée aux amandes et noisettes.',
    category: 'Snacks',
    price: 22000,
    ingredients: [
      'Farine',
      'Beurre',
      'Œufs',
      'Praline',
      'Amandes',
      'Noisettes',
    ],
    preparationTime: 150,
    rating: 4.9,
    isAvailable: true,
  },
  {
    id: '7',
    title: 'Koba Ravina Chocolat',
    description: 'Version moderne du koba avec du chocolat.',
    category: 'Gâteau',
    price: 7000,
    ingredients: ['Cacahuètes', 'Bananes', 'Riz', 'Chocolat', 'Miel'],
    preparationTime: 140,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: '8',
    title: 'Tarte aux fruits exotiques',
    description: 'Tarte garnie de fruits exotiques de Madagascar.',
    category: 'Gâteau',
    price: 18000,
    ingredients: [
      'Pâte sucrée',
      'Litchi',
      'Mangue',
      'Fruit du dragon',
      'Crème pâtissière',
    ],
    preparationTime: 90,
    rating: 4.8,
    isAvailable: false,
  },
  {
    id: '9',
    title: 'Menakely',
    description: 'Petits gâteaux rouges traditionnels malgaches.',
    category: 'Snacks',
    price: 3000,
    ingredients: ['Farine', 'Sucre', 'Œufs', 'Colorant rouge', 'Vanille'],
    preparationTime: 60,
    rating: 4.5,
    isAvailable: true,
  },
  {
    id: '10',
    title: 'Crème brûlée à la vanille de Madagascar',
    description:
      'Crème à la vanille de Madagascar avec surface de caramel craquant.',
    category: 'Gâteau',
    price: 19000,
    ingredients: ['Crème', 'Vanille de Madagascar', 'Œufs', 'Sucre'],
    preparationTime: 60,
    rating: 4.9,
    isAvailable: true,
  },
  {
    id: '11',
    title: 'Mofo Gasy',
    description: 'Petites crêpes épaisses traditionnelles malgaches.',
    category: 'Snacks',
    price: 1000,
    ingredients: ['Farine', 'Sucre', 'Levure', 'Lait', 'Vanille'],
    preparationTime: 30,
    rating: 4.6,
    isAvailable: true,
  },
  {
    id: '12',
    title: 'Mille-feuille aux fruits rouges',
    description: 'Pâte feuilletée et crème avec fruits rouges frais.',
    category: 'Gâteau',
    price: 20000,
    ingredients: [
      'Pâte feuilletée',
      'Crème pâtissière',
      'Fruits rouges',
      'Sucre glace',
    ],
    preparationTime: 120,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: '13',
    title: 'Ravitoto Chocolat',
    description:
      'Dessert fusion combinant le manioc traditionnel et le chocolat.',
    category: 'Gâteau',
    price: 8000,
    ingredients: ['Manioc', 'Chocolat', 'Lait de coco', 'Sucre', 'Vanille'],
    preparationTime: 90,
    rating: 4.5,
    isAvailable: true,
  },
  {
    id: '14',
    title: 'Macarons aux épices malgaches',
    description: 'Macarons parfumés aux épices de Madagascar.',
    category: 'Snacks',
    price: 12000,
    ingredients: [
      "Poudre d'amande",
      'Sucre glace',
      "Blanc d'œuf",
      'Épices malgaches',
      'Crème',
    ],
    preparationTime: 150,
    rating: 4.8,
    isAvailable: true,
  },
  {
    id: '15',
    title: 'Jus de canne à sucre glacé',
    description: 'Dessert glacé à base de jus de canne à sucre frais.',
    category: 'Boisson',
    price: 5000,
    ingredients: ['Canne à sucre', 'Citron vert', 'Glace pilée', 'Menthe'],
    preparationTime: 20,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: '16',
    title: 'Tarte au chocolat et litchi',
    description:
      'Tarte au chocolat noir garnie de litchis frais de Madagascar.',
    category: 'Gâteau',
    price: 17000,
    ingredients: ['Chocolat noir', 'Litchi', 'Crème', 'Pâte sucrée', 'Beurre'],
    preparationTime: 100,
    rating: 4.8,
    isAvailable: true,
  },
  {
    id: '17',
    title: 'Bonbon Cravate',
    description: 'Petits gâteaux traditionnels en forme de cravate.',
    category: 'Snacks',
    price: 2500,
    ingredients: ['Farine', 'Sucre', 'Œufs', 'Vanille', 'Huile'],
    preparationTime: 45,
    rating: 4.6,
    isAvailable: true,
  },
  {
    id: '18',
    title: 'Gâteau au miel et baobab',
    description:
      'Gâteau moderne utilisant du miel local et de la poudre de fruit de baobab.',
    category: 'Gâteau',
    price: 15000,
    ingredients: ['Farine', 'Miel', 'Poudre de baobab', 'Œufs', 'Beurre'],
    preparationTime: 75,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: '19',
    title: 'Krème glacée vanille-café',
    description:
      'Crème glacée artisanale à la vanille de Madagascar et café local.',
    category: 'Snacks',
    price: 9000,
    ingredients: [
      'Crème',
      'Vanille de Madagascar',
      'Café local',
      'Sucre',
      'Lait',
    ],
    preparationTime: 240,
    rating: 4.8,
    isAvailable: true,
  },
];
